### ISSUE TITLE
How will we download artifacts required by the makefile?

### ISSUE THREAD

**Issue by jmalloc** [make-files/makefiles#2]
We need to be able to download the makefiles themselves, as well as any additional artifacts, such as bash scripts that the makefile depends on.

My current implementations tend to use a bash script that performs the downloading, such as the Dogmatic makefiles [fetch script](https://github.com/dogmatiq/makefiles/blob/master/fetch).

This is executed by the makefile by piping it to bash:

```Makefile
artifacts/make/%.mk:
	curl -sf https://dogmatiq.io/makefiles/fetch | bash /dev/stdin $*
```

Notice that both the makefile and the fetch script depend on `curl`, which is probably the lowest common denominator. The `fetch` script could contain some smarts to use other downloading mechanisms if they are available, but the makefile itself will always need to get the original binary somehow.

As for other assets, it might be possible to define such a pattern rule that can download any file from the repo, by reserving some subfolder of `artifacts/` for this purpose. For example, `artifacts/make/foo/bar.ext` would always be pulled from `make-files.github.io/foo/bar.ext` or something like that.

Another solution we've used elsewhere is to download all assets in a single archive.

**Comment by ezzatron** [comment]
> For example, `artifacts/make/foo/bar.ext` would always be pulled from `make-files.github.io/foo/bar.ext` or something like that.

Seems like a workable solution to me. We could also generalize it into a system for any web asset, where `artifacts/remote/https/example.org/path/to/file` could be pulled from `https://example.org/path/to/file`?

**Comment by jmalloc** [comment]
Yeah potentially. It'd probably be a mistake to tie those two systems together, but it could work.
