### ISSUE TITLE
How will we version makefiles?

### ISSUE THREAD

**Issue by jmalloc** [make-files/makefiles#3]

**Comment by jmalloc** [comment]
In trying to put something basic together, I think there's really 4 "things" that are being versioned.

1. The `fetch` script - that is, the code used to download other Makefiles/resources
2. The "spec" that defines what targets we expect to have available across all languages
3. The language specific makefile, even if it conforms to a certain version of the "spec" it may have other language-specific BC breaks over time
4. The language itself (e.g., Go 1 vs Go 2, which might well have incompatible tooling)

**Comment by jmalloc** [comment]
I had started down the path of versioning the fetch script (1), but I wonder if this is one that we can avoid, or perhaps roll into (2) such that the "spec" covers the repository layout (where the fetch files puts things) and the standardized target names, I think this makes sense.

For (4) I think it makes sense to just treat these as separate languages, that is, have separate `go1` and `go2` libraries where the version number is just part of the name and is otherwise meaningless to the system.

**Comment by jmalloc** [comment]
Here's what I've landed on for a "v1" (which I am actually considering renaming to a `v0` to allow rapid changes as per semver):

- The GitHub pages repo (and hence https://makefiles.dev) contains a download script, named for the version of the overall Makefile system, for example: https://makefiles.dev/v1
- This script downloads the content of the [core library](https://github.com/make-files/lib-core)
- The core library contains a common makefile, as well as a set of ancillary scripts
- Some of these scripts can download other libraries or packages
- A library is a repo named `make-files/lib-<something>`, with a branch name matching the version of the Makefile system. That is, if you use the `v1` downloader script you will always get `v1` of a library. 
- A package is a repo named `make-files/pkg-<something>`. Packages are versioned independently from the Makefile system and its libraries. There is currently no mechanism that ensures a given package version is intended to work with a specific Makefiles version, but this could be added.

**Comment by jmalloc** [comment]
Also, every library and package has branches named `vN`, without a `master`.

**Comment by ezzatron** [comment]
So what's the intended difference between a library and a package?

**Comment by jmalloc** [comment]
It's about the versioning... libraries are extensions to version X of the makefile system itself, such as Travis CI specific scripts. Whereas packages are programming-language-specific and versioned independently.

**Comment by jmalloc** [comment]
The idea of libraries could be dropped without affecting BC... it's "packages" that the end user sees.
